# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 09:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='mobile_number',
            field=models.CharField(default=7405505665, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
