# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 10:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180115_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
