# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170929_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=100),
        ),
    ]
